services:
  - type: web
    name: my-n8n-server
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: mrzawmovie2026recapkey
      - key: PATH
        value: /opt/render/project/src/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
